version: "3"

vars:
  BINARY_NAME:
    sh: |
      if [ "{{OS}}" = "windows" ]; then
        echo "lzp.exe"
      else
        echo "lzp"
      fi

tasks:
  build:
    deps: [generate-header]
    cmds:
      - |
        {{- if eq OS "windows" -}}
        gcc -O3 lzp.c mpc.c lzp_core.c -o {{.BINARY_NAME}} -Wl,--stack,16777216
        {{- else -}}
        gcc -O3 lzp.c mpc.c lzp_core.c -o {{.BINARY_NAME}} -lm -lreadline
        {{- end -}}
    sources:
      - prelude.h
      - lzp.c
      - mpc.c
      - lzp_core.h
      - lzp_core.c
    generates:
      - "{{ .BINARY_NAME }}"

  generate-header:
    cmds:
      - xxd -i prelude.lzp > prelude.h
    sources:
      - prelude.lzp
    generates:
      - prelude.h

  run:
    deps: [build]
    cmds:
      - ./{{.BINARY_NAME}}

  test:
    deps: [build]
    cmds:
      - ./{{.BINARY_NAME}} -n ./tests/builtin.lzp

  plugin:build:all:
    deps:
      - plugin:build:time

  plugin:build:time:
    cmds:
      - xxd -n time_script -i ./plugins/time.lzp > ./plugins/time.h
      - |
        {{- if eq OS "windows" -}}
        gcc -shared -O3 -o ./plugins/time.lpp ./plugins/time.c ./lzp_core.c ./mpc.c
        {{- else -}}
        gcc -fPIC -shared -O3 -o ./plugins/time.lpp ./plugins/time.c ./lzp_core.c ./mpc.c
        {{- end -}}
    sources:
      - ./plugins/time.lpp
      - lzp_core.c
      - mpc.c
      - time.lzp
    generates:
      - ./plugins/time.lpp
